### ISSUE TITLE
Add testing with Travis

### ISSUE THREAD

**Issue by dosumis** [VirtualFlyBrain/FlyLight-Split-GAL4-Curation#10]
1. Create a `.travis.yml` file at the top level of your repo, modelled on this https://github.com/obophenotype/CCF_tools/blob/master/.travis.yml - but with the script switched to yours + args.  If you write specific code tests later, these can go here too.

2. Add a `requirements.txt` file to the top level of your repo with any external libraries you are using.  This is just a list of the external python libs you are using (those that need to be installed from pip).  e.g. https://github.com/obophenotype/CCF_tools/blob/master/requirements.txt
I think the only dependency you have right now is `pandas`.

3. Add a badge to your README.md modelling on this:
https://github.com/obophenotype/CCF_tools/edit/master/README.md

If you have trouble getting travis to run - let me know & I'll link it up.

**Comment by admclachlan** [comment]
Travis is linked, testing failing though, I think due to the yaml library 3cbb687dbde9797d634f7a25109f3755d2a2d1b3.

**Comment by dosumis** [comment]
just add it to requirements.txt

**Comment by admclachlan** [comment]
Testing working and current commit passed 090e4f1cd37a1bd07d92d3363c97686a8779aacc. It's only testing with a single set of args at the moment, but I think that is enough to find most errors.

**Comment by admclachlan** [comment]
Will probably need replacing with github actions
